CREATE TABLE CUSTOMER(
       CUSTID VARCHAR2(20) PRIMARY KEY,
       PASSWORD VARCHAR2(20) NOT NULL,
       NAME VARCHAR2(30) NOT NULL,
       EMAIL VARCHAR2(30),
       DIVISION VARCHAR2(30) NOT NULL,
       IDNO VARCHAR2(20) UNIQUE,
       ADDRESS VARCHAR2(100)
)

CREATE SEQUENCE BOARD2_SEQ

CREATE TABLE BOARD2(
       BOARDNUM NUMBER PRIMARY KEY,
       ID VARCHAR2(20),
       TITLE VARCHAR2(100) NOT NULL,
       CONTENT VARCHAR2(2000) NOT NULL,
       INPUTDATE DATE DEFAULT(SYSDATE),
       HITS NUMBER DEFAULT(0)
)

CREATE SEQUENCE REPLY2_SEQ

CREATE TABLE REPLY2(
       REPLYNUM NUMBER PRIMARY KEY,
       BOARDNUM NUMBER REFERENCES BOARD2(BOARDNUM),
       ID VARCHAR2(20) NOT NULL,
       TEXT VARCHAR2(200) NOT NULL,
       INPUTDATE DATE DEFAULT(SYSDATE)
)


select * from CUSTOMER;


select * from board2;






